# Generated by Django 5.2.4 on 2025-11-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_policy", "0002_alter_flagcondition_summary_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTypeDeactivationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Content type name that should trigger deactivation (e.g., 'Commercial', 'Advertisement')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["content_type"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="audio_polic_is_acti_883959_idx"
                    ),
                    models.Index(
                        fields=["content_type"], name="audio_polic_content_ba758a_idx"
                    ),
                ],
            },
        ),
    ]
