# Generated by Django 5.2.4 on 2025-11-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0004_generalsetting_content_type_prompt"),
        ("audio_policy", "0003_contenttypedeactivationrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contenttypedeactivationrule",
            options={"ordering": ["channel", "content_type"]},
        ),
        migrations.AddField(
            model_name="contenttypedeactivationrule",
            name="channel",
            field=models.ForeignKey(
                default=1,
                help_text="Channel this rule applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_type_deactivation_rules",
                to="acr_admin.channel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contenttypedeactivationrule",
            name="content_type",
            field=models.CharField(
                help_text="Content type name that should trigger deactivation (e.g., 'Commercial', 'Advertisement')",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contenttypedeactivationrule",
            unique_together={("channel", "content_type")},
        ),
        migrations.AddIndex(
            model_name="contenttypedeactivationrule",
            index=models.Index(
                fields=["channel", "is_active"], name="audio_polic_channel_b911f1_idx"
            ),
        ),
    ]
