# Generated by Django 5.2.4 on 2025-12-12 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_policy", "0004_alter_contenttypedeactivationrule_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flagcondition",
            name="sentiment_max",
        ),
        migrations.RemoveField(
            model_name="flagcondition",
            name="sentiment_min",
        ),
        migrations.AddField(
            model_name="flagcondition",
            name="sentiment_max_lower",
            field=models.FloatField(
                blank=True,
                help_text="Lower bound for maximum sentiment value (0-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="flagcondition",
            name="sentiment_max_upper",
            field=models.FloatField(
                blank=True,
                help_text="Upper bound for maximum sentiment value (0-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="flagcondition",
            name="sentiment_min_lower",
            field=models.FloatField(
                blank=True,
                help_text="Lower bound for minimum sentiment value (0-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="flagcondition",
            name="sentiment_min_upper",
            field=models.FloatField(
                blank=True,
                help_text="Upper bound for minimum sentiment value (0-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="flagcondition",
            name="target_sentiments",
            field=models.IntegerField(
                blank=True,
                help_text="Target sentiment integer value to match (0-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
