# Generated by Django 5.2.4 on 2025-12-12 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audio_policy", "0005_remove_flagcondition_sentiment_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flagcondition",
            name="name",
        ),
    ]
