# Generated by Django 5.2.4 on 2025-10-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredefinedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the predefined filter", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this filter is used for",
                        null=True,
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list,
                        help_text="List of days of the week (e.g., ['monday', 'tuesday', 'wednesday'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this filter is currently active",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Who created this filter",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Predefined Filter",
                "verbose_name_plural": "Predefined Filters",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the shift (e.g., 'Morning Shift', 'Night Shift')",
                        max_length=100,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Start time of the shift")),
                ("end_time", models.TimeField(help_text="End time of the shift")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the shift",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this shift is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="FilterSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time for this schedule"),
                ),
                ("end_time", models.TimeField(help_text="End time for this schedule")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes for this specific schedule",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "predefined_filter",
                    models.ForeignKey(
                        help_text="The predefined filter this schedule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="shift_analysis.predefinedfilter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filter Schedule",
                "verbose_name_plural": "Filter Schedules",
                "ordering": ["start_time"],
                "unique_together": {("predefined_filter", "start_time", "end_time")},
            },
        ),
    ]
