# Generated by Django 5.2.4 on 2025-10-14 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0002_remove_wellnessbucket_bucket_id_and_more"),
        ("shift_analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filterschedule",
            options={
                "ordering": ["day_of_week", "start_time"],
                "verbose_name": "Filter Schedule",
                "verbose_name_plural": "Filter Schedules",
            },
        ),
        migrations.AlterUniqueTogether(
            name="filterschedule",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="predefinedfilter",
            name="days_of_week",
        ),
        migrations.AddField(
            model_name="filterschedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                default="monday",
                help_text="Day of the week this schedule applies to",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="predefinedfilter",
            name="channel",
            field=models.ForeignKey(
                default=1,
                help_text="Channel this filter belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predefined_filters",
                to="acr_admin.channel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="predefinedfilter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this filter",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_filters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filterschedule",
            unique_together={
                ("predefined_filter", "day_of_week", "start_time", "end_time")
            },
        ),
    ]
