# Generated by Django 5.2.4 on 2025-10-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shift_analysis", "0002_alter_filterschedule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predefinedfilter",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone for interpreting schedules",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shift",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone for interpreting start/end times",
                max_length=64,
            ),
            preserve_default=False,
        ),
    ]
