# Generated by Django 5.2.4 on 2025-10-21 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shift_analysis", "0003_predefinedfilter_timezone_shift_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="timezone",
        ),
        migrations.AddField(
            model_name="shift",
            name="days",
            field=models.CharField(
                default="monday,tuesday,wednesday,thursday,friday,saturday,sunday",
                help_text="Comma-separated days of the week (e.g., 'monday,tuesday,wednesday')",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shift",
            name="flag_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration of the shift in seconds, used to flag audio segment time data based on duration",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
