# Generated by Django 5.2.4 on 2025-10-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0003_channel_timezone"),
        ("shift_analysis", "0004_remove_shift_timezone_shift_days_shift_flag_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="channel",
            field=models.ForeignKey(
                default=1,
                help_text="Channel this shift belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="acr_admin.channel",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("name", "channel")},
        ),
    ]
