# Generated by Django 5.2.4 on 2025-10-27 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shift_analysis", "0005_shift_channel_alter_shift_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predefinedfilter",
            name="timezone",
        ),
    ]
