# Generated by Django 5.2.4 on 2025-11-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shift_analysis", "0006_remove_predefinedfilter_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="should_transcribe",
            field=models.BooleanField(
                default=False,
                help_text="Whether audio during this shift requires transcription",
            ),
        ),
    ]
