# Generated by Django 5.2.4 on 2025-11-07 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shift_analysis", "0007_shift_should_transcribe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="should_transcribe",
        ),
    ]
