# Generated by Django 5.2.4 on 2026-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbackup',
            name='pg_dump_version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
