# Generated by Django 5.2.4 on 2025-07-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("channel_id", models.CharField(max_length=255, unique=True)),
                ("project_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("openai_api_key", models.CharField(max_length=255)),
                ("openai_org_id", models.CharField(max_length=255)),
                ("arc_cloud_api_key", models.CharField(max_length=255)),
                ("revai_access_token", models.CharField(max_length=255)),
                ("summarize_transcript_prompt", models.TextField()),
                ("sentiment_analysis_prompt", models.TextField()),
                ("general_topics_prompt", models.TextField()),
                ("iab_topics_prompt", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WellnessBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "prompt",
                    models.TextField(
                        help_text="Prompt to use when analyzing transcript for this bucket"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BucketSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="acr_admin.wellnessbucket",
                    ),
                ),
            ],
        ),
    ]
