# Generated by Django 5.2.4 on 2025-07-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("channel_id", models.CharField(max_length=255)),
                ("project_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openai_api_key", models.CharField(max_length=255)),
                ("openai_org_id", models.CharField(max_length=255)),
                ("arc_cloud_api_key", models.CharField(max_length=255)),
                ("revai_access_token", models.CharField(max_length=255)),
                ("summarize_transcript_prompt", models.TextField()),
                ("sentiment_analysis_prompt", models.TextField()),
                ("general_topics_prompt", models.TextField()),
                ("iab_topics_prompt", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RevTranscriptionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("job_name", models.CharField(max_length=255)),
                ("media_url", models.URLField(max_length=512)),
                ("status", models.CharField(max_length=50)),
                ("created_on", models.DateTimeField()),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("job_type", models.CharField(default="async", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("strict_custom_vocabulary", models.BooleanField(default=False)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("failure", models.CharField(blank=True, max_length=100, null=True)),
                ("failure_detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnrecognizedAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.BigIntegerField(
                        help_text="Start time as numeric value (e.g., 202507100328)"
                    ),
                ),
                (
                    "end_time",
                    models.BigIntegerField(
                        help_text="End time as numeric value (e.g., 202507100328)"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                ("media_path", models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WellnessBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "prompt",
                    models.TextField(
                        help_text="Prompt to use when analyzing transcript for this bucket"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rev_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_detail",
                        to="acr_admin.revtranscriptionjob",
                    ),
                ),
                (
                    "unrecognized_audio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_detail",
                        to="acr_admin.unrecognizedaudio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BucketSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="acr_admin.wellnessbucket",
                    ),
                ),
            ],
        ),
    ]
