# Generated by Django 5.2.4 on 2025-07-30 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wellnessbucket",
            name="bucket_id",
        ),
        migrations.RemoveField(
            model_name="wellnessbucket",
            name="prompt",
        ),
    ]
