# Generated by Django 5.2.4 on 2025-07-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0002_remove_generalsetting_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_id",
            field=models.CharField(max_length=255),
        ),
    ]
