# Generated by Django 5.2.4 on 2025-07-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0002_alter_generalsetting_arc_cloud_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("sentiment", models.CharField(max_length=50)),
                (
                    "general_topics",
                    models.TextField(
                        help_text="General topics identified in the transcript"
                    ),
                ),
                (
                    "iab_topics",
                    models.TextField(
                        help_text="IAB topics identified in the transcript"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcription_detail",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="acr_admin.transcriptiondetail",
                    ),
                ),
            ],
        ),
    ]
