# Generated by Django 5.2.4 on 2025-07-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0003_alter_channel_channel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnrecognizedAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                ("media_path", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unrecognized_audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcriptions",
                        to="acr_admin.unrecognizedaudio",
                    ),
                ),
            ],
        ),
    ]
