# Generated by Django 5.2.4 on 2025-07-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0004_generalsetting_bucket_definition_error_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsetting",
            name="chatgpt_model",
            field=models.CharField(
                blank=True,
                default="gpt-3.5-turbo",
                help_text="ChatGPT model to use for classification (e.g., gpt-40).",
                max_length=100,
                null=True,
            ),
        ),
    ]
