# Generated by Django 5.2.4 on 2025-07-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0004_unrecognizedaudio_transcriptiondetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevTranscriptionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("job_name", models.CharField(max_length=255)),
                ("media_url", models.URLField(max_length=512)),
                ("status", models.CharField(max_length=50)),
                ("created_on", models.DateTimeField()),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("job_type", models.CharField(default="async", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("strict_custom_vocabulary", models.BooleanField(default=False)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("failure", models.CharField(blank=True, max_length=100, null=True)),
                ("failure_detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
