# Generated by Django 5.2.4 on 2025-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0004_generalsetting_content_type_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellnessbucket",
            name="category",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("community", "Community"),
                    ("spiritual", "Spiritual"),
                ],
                default="personal",
                help_text="Category for dashboard classification",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
