# Generated by Django 5.2.4 on 2025-07-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0005_revtranscriptionjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unrecognizedaudio",
            name="end_time",
            field=models.BigIntegerField(
                help_text="End time as numeric value (e.g., 202507100328)"
            ),
        ),
        migrations.AlterField(
            model_name="unrecognizedaudio",
            name="start_time",
            field=models.BigIntegerField(
                help_text="Start time as numeric value (e.g., 202507100328)"
            ),
        ),
    ]
