# Generated by Django 5.2.4 on 2025-07-25 15:01

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0005_alter_generalsetting_chatgpt_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalsetting",
            name="arc_cloud_api_key",
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="acr_cloud_api_key",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="generalsetting",
            name="openai_api_key",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="generalsetting",
            name="revai_access_token",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
    ]
