# Generated by Django 5.2.4 on 2025-12-29 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0005_wellnessbucket_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalsetting",
            options={
                "verbose_name": "General Setting",
                "verbose_name_plural": "General Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="wellnessbucket",
            options={
                "verbose_name": "Wellness Bucket",
                "verbose_name_plural": "Wellness Buckets",
            },
        ),
        migrations.AlterModelTable(
            name="generalsetting",
            table="general_setting",
        ),
        migrations.AlterModelTable(
            name="wellnessbucket",
            table="wellness_bucket",
        ),
    ]
