# Generated by Django 5.2.4 on 2026-01-01 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0006_alter_generalsetting_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalsetting",
            name="chatgpt_frequency_penalty",
        ),
        migrations.RemoveField(
            model_name="generalsetting",
            name="chatgpt_presence_penalty",
        ),
        migrations.RemoveField(
            model_name="generalsetting",
            name="radio_segment_types",
        ),
        migrations.RemoveField(
            model_name="generalsetting",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="change_reason",
            field=models.TextField(
                blank=True,
                help_text="Optional reason for creating this version.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when this version was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this version.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="general_settings_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this version is currently active. Only one version can be active at a time.",
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous version that this version was created from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_versions",
                to="acr_admin.generalsetting",
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Version number for this settings configuration."
            ),
        ),
        migrations.AddField(
            model_name="wellnessbucket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when this bucket was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wellnessbucket",
            name="general_setting",
            field=models.ForeignKey(
                default=1,
                help_text="General settings version this bucket belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wellness_buckets",
                to="acr_admin.generalsetting",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wellnessbucket",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Soft delete flag for this bucket."
            ),
        ),
        migrations.AddField(
            model_name="wellnessbucket",
            name="source_bucket_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Original bucket ID when this bucket was cloned.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cloned_buckets",
                to="acr_admin.wellnessbucket",
            ),
        ),
        migrations.AddConstraint(
            model_name="generalsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="only_one_active_general_setting",
            ),
        ),
        migrations.AddConstraint(
            model_name="wellnessbucket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("general_setting", "title"),
                name="unique_bucket_title_per_version",
            ),
        ),
    ]
