# Generated by Django 5.2.4 on 2025-07-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0006_alter_unrecognizedaudio_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptiondetail",
            name="rev_job",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcription_detail",
                to="acr_admin.revtranscriptionjob",
            ),
            preserve_default=False,
        ),
    ]
