# Generated by Django 5.2.4 on 2025-07-29 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0006_remove_generalsetting_arc_cloud_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unrecognizedaudio",
            name="channel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unrecognized_audios",
                to="acr_admin.channel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unrecognizedaudio",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="unrecognizedaudio",
            name="end_time",
            field=models.DateTimeField(help_text="End time as datetime"),
        ),
        migrations.AlterField(
            model_name="unrecognizedaudio",
            name="start_time",
            field=models.DateTimeField(help_text="Start time as datetime"),
        ),
    ]
