# Generated by Django 5.2.4 on 2025-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0007_transcriptiondetail_rev_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unrecognizedaudio",
            name="media_path",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
