# Generated by Django 5.2.4 on 2025-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0007_unrecognizedaudio_channel_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                fields=("channel_id", "project_id"), name="unique_channel_per_project"
            ),
        ),
    ]
