# Generated by Django 5.2.4 on 2025-07-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0008_channel_unique_channel_per_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_id",
            field=models.PositiveIntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name="channel",
            name="project_id",
            field=models.PositiveIntegerField(max_length=255),
        ),
    ]
