# Generated by Django 5.2.4 on 2025-07-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0008_alter_unrecognizedaudio_media_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcriptiondetail",
            name="unrecognized_audio",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcription_detail",
                to="acr_admin.unrecognizedaudio",
            ),
        ),
    ]
