# Generated by Django 5.2.4 on 2025-07-30 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0009_alter_channel_channel_id_alter_channel_project_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcriptiondetail",
            name="rev_job",
        ),
        migrations.RemoveField(
            model_name="transcriptionanalysis",
            name="transcription_detail",
        ),
        migrations.RemoveField(
            model_name="transcriptiondetail",
            name="unrecognized_audio",
        ),
        migrations.RemoveField(
            model_name="unrecognizedaudio",
            name="channel",
        ),
        migrations.DeleteModel(
            name="BucketSentence",
        ),
        migrations.DeleteModel(
            name="RevTranscriptionJob",
        ),
        migrations.DeleteModel(
            name="TranscriptionAnalysis",
        ),
        migrations.DeleteModel(
            name="TranscriptionDetail",
        ),
        migrations.DeleteModel(
            name="UnrecognizedAudio",
        ),
    ]
