# Generated by Django 5.2.4 on 2026-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_automation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptrun",
            name="status",
        ),
        migrations.AddField(
            model_name="promptresult",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="promptresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="promptresult",
            name="response",
            field=models.TextField(blank=True),
        ),
    ]
