# Generated by Django 5.2.4 on 2026-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_automation', '0002_remove_promptrun_status_promptresult_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrun',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
