# Generated by Django 5.2.4 on 2025-10-03 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioUnrecognizedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Unrecognized Audio Category",
                "verbose_name_plural": "Unrecognized Audio Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TitleMappingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "before_title",
                    models.CharField(
                        db_index=True,
                        help_text="String or pattern to match against segment title_before",
                        max_length=255,
                    ),
                ),
                (
                    "skip_transcription",
                    models.BooleanField(
                        default=False,
                        help_text="If true, segments matching this rule are excluded from transcription",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="segmentor.audiounrecognizedcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Title Mapping Rule",
                "verbose_name_plural": "Title Mapping Rules",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="segmentor_t_is_acti_8edefa_idx"
                    )
                ],
            },
        ),
    ]
