# Generated by Django 5.2.4 on 2025-10-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segmentor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titlemappingrule",
            name="skip_transcription",
            field=models.BooleanField(
                default=True,
                help_text="If true, segments matching this rule are excluded from transcription",
            ),
        ),
    ]
