# Generated by Django 5.2.4 on 2025-10-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0002_remove_wellnessbucket_bucket_id_and_more"),
        ("segmentor", "0002_alter_titlemappingrule_skip_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiounrecognizedcategory",
            name="channel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unrecognized_categories",
                to="acr_admin.channel",
            ),
            preserve_default=False,
        ),
    ]
