# Generated by Django 5.2.4 on 2025-10-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segmentor", "0003_audiounrecognizedcategory_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlemappingrule",
            name="after_title",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="String or pattern to match against segment title_after",
                max_length=255,
            ),
        ),
    ]
