# Generated by Django 5.2.4 on 2025-10-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0003_channel_timezone"),
        ("segmentor", "0004_titlemappingrule_after_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiounrecognizedcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="audiounrecognizedcategory",
            constraint=models.UniqueConstraint(
                fields=("name", "channel"), name="unique_category_name_per_channel"
            ),
        ),
    ]
