# Generated by Django 5.2.4 on 2025-07-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("acr_admin", "0010_remove_transcriptiondetail_rev_job_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevTranscriptionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("job_name", models.CharField(max_length=255)),
                ("media_url", models.URLField(max_length=512)),
                ("status", models.CharField(max_length=50)),
                ("created_on", models.DateTimeField()),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("job_type", models.CharField(default="async", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("strict_custom_vocabulary", models.BooleanField(default=False)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("failure", models.CharField(blank=True, max_length=100, null=True)),
                ("failure_detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rev_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_detail",
                        to="data_analysis.revtranscriptionjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("sentiment", models.CharField(max_length=50)),
                (
                    "general_topics",
                    models.TextField(
                        help_text="General topics identified in the transcript"
                    ),
                ),
                (
                    "iab_topics",
                    models.TextField(
                        help_text="IAB topics identified in the transcript"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcription_detail",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="data_analysis.transcriptiondetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnrecognizedAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="Start time as datetime"),
                ),
                ("end_time", models.DateTimeField(help_text="End time as datetime")),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                ("media_path", models.CharField(max_length=512, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unrecognized_audios",
                        to="acr_admin.channel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transcriptiondetail",
            name="unrecognized_audio",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcription_detail",
                to="data_analysis.unrecognizedaudio",
            ),
        ),
    ]
