# Generated by Django 5.2.4 on 2025-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionanalysis",
            name="bucket_prompt",
            field=models.TextField(
                default="", help_text="Bucket prompt for categorization"
            ),
            preserve_default=False,
        ),
    ]
