# Generated by Django 5.2.4 on 2025-08-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0002_remove_wellnessbucket_bucket_id_and_more"),
        ("data_analysis", "0002_transcriptionanalysis_bucket_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioSegments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="Start time of the audio segment"),
                ),
                (
                    "end_time",
                    models.DateTimeField(help_text="End time of the audio segment"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                (
                    "is_recognized",
                    models.BooleanField(
                        default=False, help_text="Whether the segment was recognized"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="To store Title of recognized segments",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "title_before_id",
                    models.CharField(
                        blank=True,
                        help_text="To store the before Title of recognized segments",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "title_after_id",
                    models.CharField(
                        blank=True,
                        help_text="To store the after Title of recognized segments",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason/log/debug info",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audios_segments",
                        to="acr_admin.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
