# Generated by Django 5.2.4 on 2025-08-04 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0003_audiosegments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiosegments",
            old_name="title_after_id",
            new_name="title_after",
        ),
        migrations.RenameField(
            model_name="audiosegments",
            old_name="title_before_id",
            new_name="title_before",
        ),
    ]
