# Generated by Django 5.2.4 on 2025-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_analysis",
            "0004_rename_title_after_id_audiosegments_title_after_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the segment is active (not superseded by newer data)",
            ),
        ),
    ]
