# Generated by Django 5.2.4 on 2025-08-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0005_audiosegments_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="is_analysis_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether data analysis has been completed for this audio segment",
            ),
        ),
        migrations.AddField(
            model_name="transcriptiondetail",
            name="audio_segment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcription_detail",
                to="data_analysis.audiosegments",
            ),
        ),
        migrations.AlterField(
            model_name="transcriptiondetail",
            name="unrecognized_audio",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcription_detail",
                to="data_analysis.unrecognizedaudio",
            ),
        ),
    ]
