# Generated by Django 5.2.4 on 2025-08-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0006_audiosegments_is_analysis_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="is_audio_downloaded",
            field=models.BooleanField(
                default=False, help_text="Whether the audio file has been downloaded"
            ),
        ),
    ]
