# Generated by Django 5.2.4 on 2025-08-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0007_audiosegments_is_audio_downloaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="revtranscriptionjob",
            name="audio_segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rev_transcription_jobs",
                to="data_analysis.audiosegments",
            ),
        ),
        migrations.AddField(
            model_name="revtranscriptionjob",
            name="last_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="revtranscriptionjob",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
