# Generated by Django 5.2.4 on 2025-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0008_revtranscriptionjob_audio_segment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="metadata_json",
            field=models.JSONField(
                blank=True,
                help_text="JSON field to store metadata like artists, albums, external IDs, etc. from music recognition data",
                null=True,
            ),
        ),
    ]
