# Generated by Django 5.2.4 on 2025-09-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0009_audiosegments_metadata_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptionQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_transcribed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the transcription has been completed",
                    ),
                ),
                (
                    "is_analyzed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the analysis has been completed",
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audio_segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_queue",
                        to="data_analysis.audiosegments",
                    ),
                ),
            ],
        ),
    ]
