# Generated by Django 5.2.4 on 2025-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0010_transcriptionqueue"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(
                        help_text="Name of the general topic",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this topic should be included in results (True) or ignored (False)",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the current status", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="Who last updated this topic",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["topic_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="data_analys_is_acti_72675c_idx"
                    ),
                    models.Index(
                        fields=["topic_name"], name="data_analys_topic_n_40e202_idx"
                    ),
                ],
            },
        ),
    ]
