# Generated by Django 5.2.4 on 2025-09-10 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0011_generaltopic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcriptiondetail",
            name="unrecognized_audio",
        ),
        migrations.RemoveField(
            model_name="generaltopic",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="generaltopic",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="UnrecognizedAudio",
        ),
    ]
