# Generated by Django 5.2.4 on 2025-09-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0002_remove_wellnessbucket_bucket_id_and_more"),
        (
            "data_analysis",
            "0012_remove_transcriptiondetail_unrecognized_audio_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["channel"], name="data_analys_channel_fc2186_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["start_time"], name="data_analys_start_t_83e654_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["channel", "start_time"], name="data_analys_channel_d2ccb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["is_active"], name="data_analys_is_acti_6bc58c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["is_recognized"], name="data_analys_is_reco_0b9e1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["channel", "is_active"], name="data_analys_channel_78f73e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["file_path"], name="data_analys_file_pa_81ca25_idx"
            ),
        ),
    ]
