# Generated by Django 5.2.4 on 2025-09-17 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0013_audiosegments_data_analys_channel_fc2186_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the report folder", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the folder",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for the folder (default: blue)",
                        max_length=7,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the folder is public or private",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_public"], name="data_analys_is_publ_5de3b8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="data_analys_created_530e16_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedAudioSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_insight",
                    models.TextField(
                        blank=True,
                        help_text="Custom insight or note added by user",
                        null=True,
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="Whether this is marked as favorite"
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_in_folders",
                        to="data_analysis.audiosegments",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_segments",
                        to="data_analysis.reportfolder",
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "indexes": [
                    models.Index(
                        fields=["folder"], name="data_analys_folder__5e95a7_idx"
                    ),
                    models.Index(
                        fields=["saved_at"], name="data_analys_saved_a_5b9a9f_idx"
                    ),
                    models.Index(
                        fields=["is_favorite"], name="data_analys_is_favo_8d97c5_idx"
                    ),
                    models.Index(
                        fields=["folder", "saved_at"],
                        name="data_analys_folder__e129ef_idx",
                    ),
                ],
                "unique_together": {("folder", "audio_segment")},
            },
        ),
    ]
