# Generated by Django 5.2.4 on 2025-09-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0014_reportfolder_savedaudiosegment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedaudiosegment",
            name="custom_insight",
        ),
        migrations.CreateModel(
            name="AudioSegmentInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the insight", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the insight"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "saved_audio_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="data_analysis.savedaudiosegment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["saved_audio_segment"],
                        name="data_analys_saved_a_f3fc9e_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="data_analys_created_cddc00_idx"
                    ),
                ],
            },
        ),
    ]
