# Generated by Django 5.2.4 on 2025-09-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0015_remove_savedaudiosegment_custom_insight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="is_manually_processed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the segment was manually transcribed or analyzed",
            ),
        ),
    ]
