# Generated by Django 5.2.4 on 2025-09-25 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0016_audiosegments_is_manually_processed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the segment if manual",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_audio_segments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="audiosegments",
            name="source",
            field=models.CharField(
                choices=[("system", "System"), ("user", "User")],
                default="system",
                help_text="Who added the segment: system or user",
                max_length=10,
            ),
        ),
    ]
