# Generated by Django 5.2.4 on 2025-10-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0002_remove_wellnessbucket_bucket_id_and_more"),
        ("data_analysis", "0017_audiosegments_created_by_audiosegments_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportfolder",
            name="channel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_folders",
                to="acr_admin.channel",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="reportfolder",
            index=models.Index(
                fields=["channel"], name="data_analys_channel_77d6e7_idx"
            ),
        ),
    ]
