# Generated by Django 5.2.4 on 2025-10-31 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0003_channel_timezone"),
        ("data_analysis", "0018_reportfolder_channel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisSuppressionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_key", models.TextField(blank=True, null=True)),
                ("before_title", models.TextField(blank=True, null=True)),
                ("after_title", models.TextField(blank=True, null=True)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("suppression_end", models.DateTimeField()),
                ("next_title_override", models.TextField(blank=True, null=True)),
                ("segments_payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("finalized", "finalized"),
                            ("reinstated", "reinstated"),
                            ("expired", "expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppression_snapshots",
                        to="acr_admin.channel",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["channel", "status"],
                        name="data_analys_channel_85cb65_idx",
                    ),
                    models.Index(
                        fields=["suppression_end"],
                        name="data_analys_suppres_4e7961_idx",
                    ),
                ],
            },
        ),
    ]
