# Generated by Django 5.2.1 on 2025-11-03 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0019_analysissuppressionsnapshot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalysisSuppressionSnapshot",
        ),
    ]
