# Generated by Django 5.2.4 on 2025-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0020_delete_analysissuppressionsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiosegments",
            name="source",
            field=models.CharField(
                choices=[("system", "System"), ("user", "User"), ("merged", "Merged")],
                default="system",
                help_text="Who added the segment: system or user",
                max_length=10,
            ),
        ),
    ]
