# Generated by Django 5.2.4 on 2025-11-10 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0003_channel_timezone"),
        ("data_analysis", "0021_alter_audiosegments_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["channel", "start_time", "duration_seconds"],
                name="data_analys_channel_842fbc_idx",
            ),
        ),
    ]
