# Generated by Django 5.2.4 on 2025-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0022_audiosegments_data_analys_channel_842fbc_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionanalysis",
            name="content_type_prompt",
            field=models.TextField(
                blank=True, help_text="Content type classification result", null=True
            ),
        ),
    ]
