# Generated by Django 5.2.4 on 2025-11-18 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0004_generalsetting_content_type_prompt"),
        ("data_analysis", "0023_transcriptionanalysis_content_type_prompt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="is_delete",
            field=models.BooleanField(
                default=False,
                help_text="Whether the segment is marked for deletion (soft delete)",
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["is_delete"], name="data_analys_is_dele_182a90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["channel", "is_delete"], name="data_analys_channel_3f6f80_idx"
            ),
        ),
    ]
