# Generated by Django 5.2.4 on 2025-12-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0005_wellnessbucket_category"),
        ("data_analysis", "0024_audiosegments_is_delete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaltopic",
            name="channel",
            field=models.ForeignKey(
                default=1,
                help_text="Channel associated with this topic",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_topics",
                to="acr_admin.channel",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="generaltopic",
            index=models.Index(
                fields=["channel"], name="data_analys_channel_40d81e_idx"
            ),
        ),
    ]
