# Generated by Django 5.2.4 on 2025-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0005_wellnessbucket_category"),
        ("data_analysis", "0025_generaltopic_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generaltopic",
            name="topic_name",
            field=models.CharField(
                help_text="Name of the general topic", max_length=255
            ),
        ),
        migrations.AddConstraint(
            model_name="generaltopic",
            constraint=models.UniqueConstraint(
                fields=("topic_name", "channel"), name="unique_topic_per_channel"
            ),
        ),
    ]
