# Generated by Django 5.2.4 on 2026-01-19 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0008_alter_channel_options_and_more"),
        ("data_analysis", "0026_alter_generaltopic_topic_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_channel_fc2186_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_start_t_83e654_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_channel_d2ccb4_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_is_acti_6bc58c_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_is_reco_0b9e1c_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_channel_78f73e_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_file_pa_81ca25_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_channel_842fbc_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_is_dele_182a90_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiosegments",
            name="data_analys_channel_3f6f80_idx",
        ),
        migrations.AddField(
            model_name="audiosegments",
            name="audio_url",
            field=models.URLField(
                blank=True,
                help_text="Remote audio URL for podcast or custom URL audio",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="audiosegments",
            name="rss_guid",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier (GUID) from RSS feed for podcast episodes",
                max_length=512,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="audiosegments",
            name="segment_type",
            field=models.CharField(
                choices=[
                    ("broadcast", "Broadcast"),
                    ("podcast", "Podcast"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                default="broadcast",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="file_path",
            field=models.CharField(
                blank=True,
                help_text="Local file path for broadcast/custom uploads",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegments",
            index=models.Index(
                fields=["channel", "start_time", "end_time"],
                name="data_analys_channel_344bbc_idx",
            ),
        ),
    ]
