# Generated by Django 5.2.4 on 2026-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_analysis",
            "0027_remove_audiosegments_data_analys_channel_fc2186_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="pub_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Publication date of the audio segment (e.g., podcast episode publish date)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("user", "User"),
                    ("system_merge", "System Merged"),
                    ("user_merged", "User Merged"),
                ],
                default="system",
                help_text="Who added the segment: system or user",
                max_length=15,
            ),
        ),
    ]
