# Generated by Django 5.2.4 on 2026-01-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0028_audiosegments_pub_date_alter_audiosegments_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiosegments",
            name="audio_url",
            field=models.URLField(
                blank=True,
                help_text="Remote audio URL for podcast or custom URL audio",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_audio_segments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="is_recognized",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("user", "User"),
                    ("system_merge", "System Merged"),
                    ("user_merged", "User Merged"),
                ],
                default="system",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="title_after",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="audiosegments",
            name="title_before",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
