# Generated by Django 5.2.4 on 2026-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0029_alter_audiosegments_audio_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegments",
            name="audio_location_type",
            field=models.CharField(
                choices=[("file_path", "File path"), ("audio_url", "Audio URL")],
                default="file_path",
                help_text="Whether audio is served from file_path (local) or audio_url (remote)",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
