# Generated by Django 5.2.4 on 2026-09-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0030_audiosegments_audio_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegments',
            name='is_recovered_audio',
            field=models.BooleanField(default=False, help_text="Whether the segment's audio was manually uploaded (e.g. recovery of corrupted ACRCloud audio) rather than fetched by the automated pipeline"),
        ),
    ]
