# Generated by Django 5.2.4 on 2025-11-28 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSentimentPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low_sentiment_score",
                    models.PositiveIntegerField(
                        help_text="Low sentiment threshold score (0-100). Scores below this are considered low sentiment.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "high_sentiment_score",
                    models.PositiveIntegerField(
                        help_text="High sentiment threshold score (0-100). Scores above this are considered high sentiment.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "target_sentiment_score",
                    models.PositiveIntegerField(
                        help_text="Target sentiment score (0-100). The desired sentiment score the user wants to achieve.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns these sentiment preferences",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Sentiment Preference",
                "verbose_name_plural": "User Sentiment Preferences",
            },
        ),
    ]
