# Generated by Django 5.2.4 on 2025-12-29 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSentimentPreference",
        ),
    ]
