# Generated by Django 5.2.4 on 2026-06-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_radiouser_name_radiouser_password_set_magiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiouser',
            name='is_channel_admin',
            field=models.BooleanField(default=False),
        ),
    ]
