# Generated by Django 5.2.4 on 2025-12-09 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_supportticketresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportticketresponse",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="supportticketimage",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="supportticketresponse",
            name="responder",
        ),
        migrations.DeleteModel(
            name="SupportTicket",
        ),
        migrations.DeleteModel(
            name="SupportTicketImage",
        ),
        migrations.DeleteModel(
            name="SupportTicketResponse",
        ),
    ]
