# Generated by Django 5.2.1 on 2025-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0002_remove_wellnessbucket_bucket_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Timezone for the channel (e.g., America/New_York, Europe/London, UTC)",
                max_length=50,
            ),
        ),
    ]
