# Generated by Django 5.2.4 on 2025-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0003_channel_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="content_type_prompt",
            field=models.TextField(
                blank=True,
                help_text="Prompt for determining general content type from transcript.",
                null=True,
            ),
        ),
    ]
