# Generated by Django 5.2.4 on 2026-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0007_remove_generalsetting_chatgpt_frequency_penalty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
            },
        ),
        migrations.RemoveConstraint(
            model_name="channel",
            name="unique_channel_per_project",
        ),
        migrations.AddField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[("podcast", "Podcast"), ("broadcast", "Broadcast")],
                db_index=True,
                default="broadcast",
                help_text="Channel type: Podcast or Broadcast",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Soft on/off toggle for the channel"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="rss_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time from which to start processing RSS feed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="rss_url",
            field=models.URLField(
                blank=True, help_text="RSS feed location URL", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="project_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("channel_id__isnull", False),
                    ("is_deleted", False),
                    ("project_id__isnull", False),
                ),
                fields=("channel_id", "project_id"),
                name="unique_channel_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("rss_url__isnull", False)),
                fields=("rss_url",),
                name="unique_rss_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("channel_id__isnull", True),
                        ("channel_type", "podcast"),
                        ("project_id__isnull", True),
                        ("rss_url__isnull", False),
                    ),
                    models.Q(
                        ("channel_id__isnull", False),
                        ("channel_type", "broadcast"),
                        ("project_id__isnull", False),
                        ("rss_start_date__isnull", True),
                        ("rss_url__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="channel_type_consistency",
            ),
        ),
        migrations.AlterModelTable(
            name="channel",
            table="media_channel",
        ),
    ]
