# Generated by Django 5.2.4 on 2026-01-20 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0008_alter_channel_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="channel",
            name="channel_type_consistency",
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[("podcast", "Podcast"), ("broadcast", "Broadcast")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="rss_start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                help_text="Date and time from which to start processing RSS feed",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="rss_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("channel_id__isnull", True),
                        ("channel_type", "podcast"),
                        ("project_id__isnull", True),
                        ("rss_url__isnull", False),
                    ),
                    models.Q(
                        ("channel_id__isnull", False),
                        ("channel_type", "broadcast"),
                        ("project_id__isnull", False),
                        ("rss_url__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="channel_type_consistency",
            ),
        ),
    ]
