# Generated by Django 5.2.4 on 2026-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0009_remove_channel_channel_type_consistency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("podcast", "Podcast"),
                    ("broadcast", "Broadcast"),
                    ("custom_audio", "Custom Audio"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
