# Generated by Django 5.2.4 on 2026-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0010_alter_channel_channel_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="channel",
            name="channel_type_consistency",
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("channel_id__isnull", True),
                        ("channel_type", "podcast"),
                        ("project_id__isnull", True),
                        ("rss_url__isnull", False),
                    ),
                    models.Q(
                        ("channel_id__isnull", False),
                        ("channel_type", "broadcast"),
                        ("project_id__isnull", False),
                        ("rss_url__isnull", True),
                    ),
                    models.Q(
                        ("channel_id__isnull", True),
                        ("channel_type", "custom_audio"),
                        ("project_id__isnull", True),
                        ("rss_url__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="channel_type_consistency",
            ),
        ),
    ]
