# Generated by Django 5.2.4 on 2026-02-10 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0011_remove_channel_channel_type_consistency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="generalsetting",
            name="only_one_active_general_setting",
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="channel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_settings",
                to="acr_admin.channel",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="generalsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("channel", "is_active"),
                name="only_one_active_general_setting",
            ),
        ),
    ]
