# Generated by Django 5.2.4 on 2026-02-10 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "acr_admin",
            "0012_remove_generalsetting_only_one_active_general_setting_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="generalsetting",
            constraint=models.UniqueConstraint(
                fields=("channel", "version"), name="unique_channel_version"
            ),
        ),
    ]
