# Generated by Django 5.2.4 on 2026-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0013_generalsetting_unique_channel_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_default_settings",
            field=models.BooleanField(
                default=False,
                help_text="When True, this channel settings is used as default settings",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_default_settings", True), ("is_deleted", False)
                ),
                fields=("is_default_settings",),
                name="only_one_default_channel",
            ),
        ),
    ]
