# Generated by Django 5.2.4 on 2026-02-16 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0014_channel_is_default_settings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wellnessbucket",
            name="source_bucket_id",
        ),
    ]
