# Generated by Django 5.2.4 on 2026-02-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0015_remove_wellnessbucket_source_bucket_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), models.Q(("name", ""), _negated=True)
                ),
                fields=("name",),
                name="unique_channel_name",
            ),
        ),
    ]
