# Generated by Django 5.2.4 on 2026-02-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_admin", "0016_channel_unique_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="custom_vocabulary",
            field=models.JSONField(
                blank=True, default=list, help_text="List of custom vocabulary phrases."
            ),
        ),
    ]
