# Generated by Django 5.2.4 on 2026-09-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acr_admin', '0017_generalsetting_custom_vocabulary'),
        ('data_analysis', '0031_audiosegments_is_recovered_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveredAudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('file_name', models.CharField(max_length=512)),
                ('file_path', models.CharField(blank=True, help_text='Where the full downloaded file is stored', max_length=512)),
                ('recorded_at', models.DateTimeField(help_text='UTC start time of the recording')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovered_audio_files', to='acr_admin.channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_audio_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveredAudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sec', models.PositiveIntegerField(help_text='Offset into the source file where this segment starts')),
                ('end_sec', models.PositiveIntegerField(help_text='Offset into the source file where this segment ends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_segment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_from', to='data_analysis.audiosegments')),
                ('recovered_audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audio_recovery.recoveredaudiofile')),
            ],
            options={
                'ordering': ['start_sec'],
            },
        ),
    ]
