# Generated by Django 5.2.4 on 2026-09-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveredaudiofile',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recoveredaudiofile',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recoveredaudiofile',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoveredaudiofile',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoveredaudiofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
