# Generated by Django 5.2.4 on 2026-09-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recovery', '0002_recoveredaudiofile_celery_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveredaudiofile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='recoveredaudiofile',
            name='file_path',
        ),
    ]
