# Generated by Django 5.2.4 on 2026-08-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acr_admin', '0017_generalsetting_custom_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_segments_per_hour', models.PositiveIntegerField(blank=True, help_text='Admin-set minimum expected segments per hour for this channel. Used to detect a corrupted/degraded ACRCloud feed (e.g. an incident where only 5-15 segments/day came in instead of the normal volume). Leave blank to skip this check.', null=True)),
                ('low_volume_alert_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_config', to='acr_admin.channel')),
            ],
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, help_text="Only notified about this channel's components (acr_ingestion, openai_billing). Leave blank to be notified about every channel plus channel-independent components (e.g. the processing pipeline backlog).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_recipients', to='acr_admin.channel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('channel__isnull', False)), fields=('email', 'channel'), name='uq_alertrecipient_email_channel'), models.UniqueConstraint(condition=models.Q(('channel__isnull', True)), fields=('email',), name='uq_alertrecipient_email_global')],
            },
        ),
        migrations.CreateModel(
            name='ComponentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('acr_ingestion', 'ACRCloud Ingestion'), ('processing_pipeline', 'Processing Pipeline'), ('openai_billing', 'OpenAI Billing')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('segments_received', models.PositiveIntegerField(blank=True, null=True)),
                ('segments_saved', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_window_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_coverage_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('coverage_ratio', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('last_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Null for channel-independent components (e.g. processing_pipeline).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='acr_admin.channel')),
            ],
            options={
                'indexes': [models.Index(fields=['component', 'channel'], name='monitoring__compone_3b87b7_idx'), models.Index(fields=['status'], name='monitoring__status_f542ba_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('channel__isnull', False)), fields=('component', 'channel'), name='uq_monitoring_component_channel'), models.UniqueConstraint(condition=models.Q(('channel__isnull', True)), fields=('component',), name='uq_monitoring_component_global')],
            },
        ),
    ]
