# Generated by Django 5.2.4 on 2025-11-24 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("acr_admin", "0004_generalsetting_content_type_prompt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlagCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the flag condition",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "transcription_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of keywords to match in transcription",
                    ),
                ),
                (
                    "summary_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of keywords to match in summary",
                    ),
                ),
                (
                    "sentiment_min",
                    models.FloatField(
                        blank=True, help_text="Minimum sentiment score", null=True
                    ),
                ),
                (
                    "sentiment_max",
                    models.FloatField(
                        blank=True, help_text="Maximum sentiment score", null=True
                    ),
                ),
                (
                    "iab_topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of IAB topics to match",
                    ),
                ),
                (
                    "bucket_prompt",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of bucket prompts to match",
                    ),
                ),
                (
                    "general_topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of general topics to match",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this condition is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.OneToOneField(
                        help_text="Channel this condition applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flag_condition",
                        to="acr_admin.channel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flag_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
