# Generated by Django 5.2.4 on 2025-11-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_flags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flagcondition",
            name="summary_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of keyword groups to match in summary",
            ),
        ),
        migrations.AlterField(
            model_name="flagcondition",
            name="transcription_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of keyword groups to match in transcription",
            ),
        ),
    ]
