# Generated by Django 5.2.4 on 2025-11-18 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_analysis", "0024_audiosegments_is_delete_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioSegmentEditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("split", "Split"),
                            ("merge", "Merge"),
                            ("adjust", "Adjust"),
                        ],
                        help_text="Type of edit that was performed",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        help_text="Whether the edit was manual or automatic",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Optional metadata (e.g., involved segment IDs, reasons)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Free-form notes or justification for the edit",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affected_segments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other audio segments participating in the edit (e.g., source segments in a merge)",
                        related_name="affected_edit_logs",
                        to="data_analysis.audiosegments",
                    ),
                ),
                (
                    "audio_segment",
                    models.ForeignKey(
                        help_text="Primary audio segment affected by this edit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_logs",
                        to="data_analysis.audiosegments",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the edit, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audio_segment_edit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["audio_segment"], name="logger_edit_audio_idx"
                    ),
                    models.Index(fields=["action"], name="logger_edit_action_idx"),
                    models.Index(
                        fields=["trigger_type"], name="logger_edit_trigger_idx"
                    ),
                ],
            },
        ),
    ]
