# Generated by Django 5.2.4 on 2026-01-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ACRCloudCustomFileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket_id",
                    models.CharField(help_text="ACR Cloud bucket ID", max_length=255),
                ),
                (
                    "audio_url",
                    models.URLField(
                        help_text="URL of the audio file uploaded", max_length=512
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the file",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                        ],
                        default="success",
                        help_text="Status of the upload operation",
                        max_length=50,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if upload failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the upload was initiated",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the upload",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acr_cloud_custom_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ACR Cloud Custom File Upload",
                "verbose_name_plural": "ACR Cloud Custom File Uploads",
                "db_table": "acr_cloud_custom_file_upload",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["bucket_id"], name="acr_cloud_c_bucket__814025_idx"
                    ),
                    models.Index(
                        fields=["status"], name="acr_cloud_c_status_1ffa38_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="acr_cloud_c_created_ea879e_idx"
                    ),
                ],
            },
        ),
    ]
