# Generated by Django 5.2.4 on 2026-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acr_cloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acrcloudcustomfileupload",
            name="file_name",
            field=models.CharField(
                blank=True,
                help_text="Original filename when uploaded as a file",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="acrcloudcustomfileupload",
            name="audio_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the audio file (when uploaded via URL); null when uploaded as file",
                max_length=512,
                null=True,
            ),
        ),
    ]
